#lang racket/base

(require "base.rkt"
         "syntax.rkt"
         "transformers.rkt"
         "inference.rkt")
(provide (all-from-out "base.rkt")
         (all-from-out "syntax.rkt")
         (all-from-out "transformers.rkt")
         (all-from-out "inference.rkt"))

(module+ test
  (require (submod lightstep/nondet test))
  (require (submod lightstep/transformers test))
  (require (submod lightstep/syntax test))
  (require (submod lightstep/inference test))

  (require (submod lightstep/examples/unit-tests scope2))

  ;; SAC'24
  (require (submod lightstep/examples/sac24/reduction/design01 test))
  (require (submod lightstep/examples/sac24/reduction/design02 test))
  (require (submod lightstep/examples/sac24/reduction/design03 test))
  (require (submod lightstep/examples/sac24/reduction/design04 test))
  (require (submod lightstep/examples/sac24/reduction/design05 test))
  (require (submod lightstep/examples/sac24/reduction/design06 test))
  (require (submod lightstep/examples/sac24/reduction/design07 test))
  (require (submod lightstep/examples/sac24/inference/design01 test))
  (require (submod lightstep/examples/sac24/inference/design02 test))
  (require (submod lightstep/examples/sac24/inference/design03 test))
  (require (submod lightstep/examples/sac24/inference/design04 test))
  (require (submod lightstep/examples/sac24/inference/design05 test))
  (require (submod lightstep/examples/sac24/inference/design06 test))
  (require (submod lightstep/examples/sac24/inference/design07 test))

  ;; winskel
  (require (submod lightstep/examples/winskel/imp test))
  (require (submod lightstep/examples/winskel/imp left-first-sequential))
  (require (submod lightstep/examples/winskel/imp parallel-or))
  (require (submod lightstep/examples/winskel/imp-state test))
  (require (submod lightstep/examples/winskel/imp-state left-first-sequential))
  (require (submod lightstep/examples/winskel/imp-state parallel-or))

  ;; redex
  (require (submod lightstep/examples/redex/reduction/b test))
  (require (submod lightstep/examples/redex/inference/b test))
  (require (submod lightstep/examples/redex/reduction/lam test))
  (require (submod lightstep/examples/redex/inference/lam test))
  (require (submod lightstep/examples/redex/reduction/iswim test))
  (require (submod lightstep/examples/redex/inference/iswim test))
  (require (submod lightstep/examples/redex/reduction/iswim-std test))
  (require (submod lightstep/examples/redex/inference/iswim-std test))
  (require (submod lightstep/examples/redex/reduction/cc test))
  (require (except-in (submod lightstep/examples/redex/inference/cc test) Ω))
  (require (submod lightstep/examples/redex/reduction/scc test))
  (require (submod lightstep/examples/redex/inference/scc test))
  (require (submod lightstep/examples/redex/reduction/ck test))
  (require (submod lightstep/examples/redex/inference/ck test))
  (require (submod lightstep/examples/redex/reduction/cek test))
  (require (submod lightstep/examples/redex/inference/cek test))
  (require (submod lightstep/examples/redex/reduction/secd test))
  (require (submod lightstep/examples/redex/inference/secd test))
  (require (submod lightstep/examples/redex/reduction/secd2 test))
  (require (submod lightstep/examples/redex/inference/secd2 test))
  (require (submod lightstep/examples/redex/reduction/secd-tco test))
  (require (submod lightstep/examples/redex/inference/secd-tco test))
  (require (submod lightstep/examples/redex/reduction/cek-ss test))
  (require (submod lightstep/examples/redex/inference/cek-ss test))
  (require (submod lightstep/examples/redex/reduction/secd-tco-ss test))
  (require (submod lightstep/examples/redex/inference/secd-tco-ss test))
  (require (submod lightstep/examples/redex/reduction/e-iswim test))
  (require (submod lightstep/examples/redex/inference/e-iswim test))
  (require (submod lightstep/examples/redex/reduction/e-iswim-std test))
  (require (submod lightstep/examples/redex/inference/e-iswim-std test))
  (require (submod lightstep/examples/redex/reduction/h-iswim test))
  (require (submod lightstep/examples/redex/inference/h-iswim test))
  (require (submod lightstep/examples/redex/reduction/h-iswim-std test))
  (require (submod lightstep/examples/redex/inference/h-iswim-std test))
  (require (submod lightstep/examples/redex/reduction/cc+h test))
  (require (submod lightstep/examples/redex/inference/cc+h test))
  (require (submod lightstep/examples/redex/reduction/chc test))
  (require (submod lightstep/examples/redex/inference/chc test))
  (require (submod lightstep/examples/redex/reduction/c-iswim test))
  (require (submod lightstep/examples/redex/inference/c-iswim test))
  (require (submod lightstep/examples/redex/reduction/c-iswim-std test))
  (require (submod lightstep/examples/redex/inference/c-iswim-std test))
  (require [submod lightstep/examples/redex/reduction/cs test])
  (require [submod lightstep/examples/redex/inference/cs test])
  (require [submod lightstep/examples/redex/reduction/s-iswim test])
  (require [submod lightstep/examples/redex/inference/s-iswim test])
  (require [submod lightstep/examples/redex/reduction/s-iswim-std test])
  (require [submod lightstep/examples/redex/inference/s-iswim-std test])
  (require [submod lightstep/examples/redex/reduction/s-iswim-std2 test])
  (require [submod lightstep/examples/redex/inference/s-iswim-std2 test])
  (require [submod lightstep/examples/redex/reduction/cs2 test])
  (require [submod lightstep/examples/redex/inference/cs2 test])
  (require [submod lightstep/examples/redex/reduction/cesk test])
  (require [submod lightstep/examples/redex/inference/cesk test])
  (require [submod lightstep/examples/redex/reduction/cs+gc test])
  (require [submod lightstep/examples/redex/inference/cs+gc test])
  (require [submod lightstep/examples/redex/reduction/cesk+gc test])
  (require [submod lightstep/examples/redex/inference/cesk+gc test])
  (require [submod lightstep/examples/redex/reduction/st-iswim test])
  (require [submod lightstep/examples/redex/inference/st-iswim test])
  (require [submod lightstep/examples/redex/reduction/rec-st-iswim test])
  (require [submod lightstep/examples/redex/inference/rec-st-iswim test])

  ;; aam
  (require (submod lightstep/examples/aam/normal/l test))
  (require (submod lightstep/examples/aam/normal/pcf test))
  (require (submod lightstep/examples/aam/normal/pcf-t test))
  (require (submod lightstep/examples/aam/normal/pcf-bigstep test))
  (require (submod lightstep/examples/aam/normal/l0 test))
  (require (submod lightstep/examples/aam/normal/l1 test))
  (require (submod lightstep/examples/aam/normal/pcf-rho test))
  (require (submod lightstep/examples/aam/normal/pcf-varsigma test))
  (require (submod lightstep/examples/aam/normal/pcf-sigma test))
  (require (submod lightstep/examples/aam/normal/pcf-sigma-alloc test))
  (require (submod lightstep/examples/aam/normal/pcf-sigma-star test))
  )
